<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Show next_ifr_AlertWin</name>
   <tag></tag>
   <elementGuidId>16b0b3a6-e305-4ece-b0ba-dddbd8f78670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifr_AlertWin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifr_AlertWin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Information Message&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>33476fc7-b948-48af-9bd2-95bd6659414a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifr_AlertWin</value>
      <webElementGuid>4fa48f34-3cc0-4e78-8f99-f45984f7cd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frames</value>
      <webElementGuid>c92d50bb-e3bd-4477-9879-91dd148d08b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Alert.jsp?MSG_TYPE=I&amp;MESSAGE=&amp;THEME=Flexblue.css&amp;OVDSCRTYP=M&amp;OVDROUTINGTYP=NX&amp;ENTITY=ENTITY_ID1</value>
      <webElementGuid>c035c59b-08a6-4cc4-a1cd-93dc5d6fe267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>2c8e9d74-fd69-4e1f-8b58-0dff0f5ce28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69c2406b-98ff-4890-97a2-85ba1612399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c6cd672e-c2e9-403f-b6f0-e783c805f248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Information Message</value>
      <webElementGuid>9f1e1290-be87-499c-bcc0-70aed73f5231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifr_AlertWin&quot;)</value>
      <webElementGuid>78e105e4-175d-40f0-ba09-916bb3cbfcca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifr_AlertWin']</value>
      <webElementGuid>9ea20b0c-61f0-4d30-bbac-a4ac0b9d3ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_AlertWin']/iframe</value>
      <webElementGuid>4a225516-ab30-4cf1-b6e5-13c93ab8d701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b3d66b2b-d3e7-4892-b22d-2d610493ff7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifr_AlertWin' and @src = 'Alert.jsp?MSG_TYPE=I&amp;MESSAGE=&amp;THEME=Flexblue.css&amp;OVDSCRTYP=M&amp;OVDROUTINGTYP=NX&amp;ENTITY=ENTITY_ID1' and @title = 'Information Message']</value>
      <webElementGuid>226dc5a2-be92-4fea-95d4-71b8fba99281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
