<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Time 153807_Ok (1)</name>
   <tag></tag>
   <elementGuidId>eaf6593a-9bf6-41cb-ad5b-e9976dfa3fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BTN_OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BTN_OK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ok&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e35cf89-ac5f-4073-b23a-4bb8175bd342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTNfooterH</value>
      <webElementGuid>0c7f5a26-0bc5-47c2-8a1b-eba55c688ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>9a203828-c3b6-43f8-b368-924e5d387865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>07d12d4a-f2c1-40ed-a753-f413347d4ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>ccccf9aa-a774-498a-9726-db68b9dff12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BTN_OK</value>
      <webElementGuid>1be317ce-76cb-40a3-b4b0-a89b0a16d3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>94dc0b35-7500-4db9-8b26-ad23bfe36a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>36557a7d-a9db-4e65-8d86-22c3ed29b388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>7b2bfdf4-9f9d-4249-9196-d5fbcf4e8494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeAlerts(event)</value>
      <webElementGuid>417410b9-995d-4700-b915-bee634ee6ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return fnHandleAlertBtn(event)</value>
      <webElementGuid>8c53763b-182f-45d0-ab05-21eb25d4d527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>b94929ea-1878-4de1-aba3-886b204199c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c101d4ba-dbfd-490f-a3eb-e5695612aa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BTN_OK&quot;)</value>
      <webElementGuid>4d0775b1-947f-47eb-b104-bc2d9c3d82c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_619d50/iframe_Show next_ifr_AlertWin_1</value>
      <webElementGuid>7450d17f-3bfc-4dbe-bb08-223ab9dcfd7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BTN_OK']</value>
      <webElementGuid>ab908f87-6b64-4c29-9b7d-9b9de374e0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TBLPageTAB_FOOTER']/tbody/tr/td[2]/input</value>
      <webElementGuid>6c14f2c5-c81f-4cc5-b7bb-6efa3927ead2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6dd65fbb-7038-4fbc-9d22-f03bfa9ff03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Ok' and @id = 'BTN_OK' and @name = 'Ok' and @type = 'button']</value>
      <webElementGuid>2440e55f-3bdd-437a-85dd-5ddb606ee6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
