<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Current Time 153807_noteTD</name>
   <tag></tag>
   <elementGuidId>1d2e90fb-5d61-4dbb-877e-8bf47fb7391f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='noteTD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#noteTD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#noteTD</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5bc0b045-ce63-418c-8b6a-428116c54b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>09a1472e-1234-4e34-bd8a-48f006452bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>98%</value>
      <webElementGuid>bb6df018-b4d7-409e-9907-e333995c4ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noteTD</value>
      <webElementGuid>bac9b998-95ed-479b-8d75-0c2899275b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noteTD&quot;)</value>
      <webElementGuid>16887828-fef5-4d7c-ae88-96fb30449532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_619d50/iframe_Show next_ifr_AlertWin</value>
      <webElementGuid>013bb113-0395-4b99-9c00-8adfa7453f6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='noteTD']</value>
      <webElementGuid>8cbbc9bf-94a6-4fdd-9253-3041aa84eca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TBLPageTAB_FOOTER']/tbody/tr/td</value>
      <webElementGuid>27cd3720-183c-4c86-86d6-21bee43ceeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>db6e4e56-897b-4d37-9153-3f954b9acd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'noteTD']</value>
      <webElementGuid>e3f6eb1a-f38d-4585-b74d-a0820058cee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
