<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Customer Details_30716915</name>
   <tag></tag>
   <elementGuidId>84b7c902-3bf8-41a6-8a2f-3eb5c806da0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifr_CustomerWin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifr_CustomerWin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\33 0716915&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>50fc4fea-78f5-4258-b6fa-75028d581a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifr_CustomerWin</value>
      <webElementGuid>d1443254-a56c-45a8-a527-3e0e5da9b2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frames</value>
      <webElementGuid>e8e521b1-6d28-4a10-8461-224055868b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>TempForward.jsp?action=SMSStartLogServlet&amp;funcid=STDCULND&amp;uiName=&amp;msgType=WORKFLOW&amp;actionType=initiate&amp;timestamp=1740065917025&amp;numeric=null&amp;parentArgs=&amp;dashboardArgs=&amp;inTime=1740065917025&amp;txnBranch=&amp;iframeLaunch=true</value>
      <webElementGuid>3dfe3b62-4830-4e63-b909-bc69fd9047fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92accd95-c05c-4bff-b17b-68c88016bbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebd1b64d-5988-434f-98b7-91228ced8594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b272be35-eb9a-4b8c-af6c-a5a9d129d9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>30716915</value>
      <webElementGuid>27fb7c10-f02f-4df0-8491-2ae94b4c380e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifr_CustomerWin&quot;)</value>
      <webElementGuid>36ab0696-70f8-413a-b873-5e334718ca91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifr_CustomerWin']</value>
      <webElementGuid>453aa938-bf47-4bb8-a209-c22fc6322f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='30716915']/iframe</value>
      <webElementGuid>617d5363-ccae-4317-a759-4f03c0aab270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f420051a-bf6a-4020-822e-d0446c2babac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifr_CustomerWin' and @src = 'TempForward.jsp?action=SMSStartLogServlet&amp;funcid=STDCULND&amp;uiName=&amp;msgType=WORKFLOW&amp;actionType=initiate&amp;timestamp=1740065917025&amp;numeric=null&amp;parentArgs=&amp;dashboardArgs=&amp;inTime=1740065917025&amp;txnBranch=&amp;iframeLaunch=true' and @name = '30716915']</value>
      <webElementGuid>75fd3cd7-14db-44b7-bc95-87f63f08bce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
