<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , ifr_LaunchWin_SEC_SUMM_21366a</name>
   <tag></tag>
   <elementGuidId>7f4ab7fb-4f32-4e2f-9033-66781ce5fe67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifr_LaunchWin_SEC_SUMMARY']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifr_LaunchWin_SEC_SUMMARY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\33 0716918&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>782f0ec9-1b3e-460b-b1c6-232a4f8b135f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>TempForward.jsp?action=SMSStartLogServlet&amp;funcid=STDCUSUM&amp;srcType=DETAIL&amp;sectionName=SEC_SUMMARY&amp;uiName=&amp;msgType=WORKFLOW&amp;actionType=initiate&amp;timestamp=&amp;numeric=&amp;parentArgs=&amp;dashboardArgs=&amp;inTime=&amp;txnBranch=&amp;debugFlag=N&amp;userLevelDbgEnabled=N</value>
      <webElementGuid>a5880e5c-1924-4bdb-a9a7-b7fdf36dc99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>83c28158-75c6-4c69-9066-d193fb359e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ae63631-0ef3-4970-8b7d-ef60565b3df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d6bc9a26-4b74-49d4-8772-5312725e9f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cdcd1a9-ca32-4c0e-9d8a-348fcfa4ff86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifr_LaunchWin_SEC_SUMMARY</value>
      <webElementGuid>827c8c07-72e8-4105-85a0-31e47be30d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>DETAIL</value>
      <webElementGuid>6e8a1b3a-aaa9-4e66-8c0b-b0da55bd18af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>30716918</value>
      <webElementGuid>83eb44ba-2e39-47e9-b061-60b0dca54162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifr_LaunchWin_SEC_SUMMARY&quot;)</value>
      <webElementGuid>457f8a24-f475-4a2a-9b84-a7e9f8854261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_1450fe/iframe_Customer Details_30716915</value>
      <webElementGuid>b4e4e36a-e55b-47a4-af5e-46f04db52b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifr_LaunchWin_SEC_SUMMARY']</value>
      <webElementGuid>9b40843c-b0fe-43fb-bc5d-b0f64514e760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='30716918']/iframe</value>
      <webElementGuid>e49f5327-a72d-40af-a209-21c9f48a6378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>284d0c54-70f3-45be-bc84-7da0bee8b8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'TempForward.jsp?action=SMSStartLogServlet&amp;funcid=STDCUSUM&amp;srcType=DETAIL&amp;sectionName=SEC_SUMMARY&amp;uiName=&amp;msgType=WORKFLOW&amp;actionType=initiate&amp;timestamp=&amp;numeric=&amp;parentArgs=&amp;dashboardArgs=&amp;inTime=&amp;txnBranch=&amp;debugFlag=N&amp;userLevelDbgEnabled=N' and @title = '0' and @id = 'ifr_LaunchWin_SEC_SUMMARY' and @type = 'DETAIL' and @name = '30716918']</value>
      <webElementGuid>de26f22d-deda-4a4d-a66c-28e372506468</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
