<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you want to Signoff_Ok (1)</name>
   <tag></tag>
   <elementGuidId>1806fec6-a96c-40db-9aa6-49f44217e8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BTN_OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BTN_OK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ok&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f18ac739-1fc5-469e-940a-2dc3b30e9a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTNfooterH</value>
      <webElementGuid>1ca35d2d-cb3c-4b39-ab67-4f7e6858a590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>c13aa370-736a-4e2a-8cbd-220af86dd0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>5c0bfab3-e462-4537-83e6-096a4768b6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>b11eaa4b-85d4-4b5a-bc4b-d9531450775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BTN_OK</value>
      <webElementGuid>b3f5853f-27f9-4a92-9935-76fb311debb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>5c83db15-540d-411c-819a-34a7a894a74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>676fdb5e-2a08-4f96-aae8-2108ee0b5263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>a14ada78-1c3f-4635-987c-9d315e1b7e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeAlerts(event)</value>
      <webElementGuid>e29c3be3-238e-4d9a-880d-a833827af335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return fnHandleAlertBtn(event)</value>
      <webElementGuid>a0a3f0b0-9aa4-432e-bfa6-24c5bfd0dede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>68adbf03-b2bd-4fdd-b362-42b9d5fa4d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9fd7372-54a2-4813-bf3f-aae2da76516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BTN_OK&quot;)</value>
      <webElementGuid>d0d13b55-5dc3-46d9-a288-2b424560ac94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_1450fe/iframe_Show next_ifr_AlertWin_1</value>
      <webElementGuid>92de786c-6ba3-4c94-b1bc-9c0cbbcb96ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BTN_OK']</value>
      <webElementGuid>7d970f6c-efb0-476b-92cb-e800ea5ef8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TBLPageTAB_FOOTER']/tbody/tr/td[2]/input</value>
      <webElementGuid>d43762ab-0650-4c7c-aafa-f2bd222d5d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>595580b6-7a37-46fc-94bf-4ffde551e524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Ok' and @id = 'BTN_OK' and @name = 'Ok' and @type = 'button']</value>
      <webElementGuid>6aa334cb-9104-4bfb-8f83-b613f0090110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
