<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Row0_FULL_NAME</name>
   <tag></tag>
   <elementGuidId>876396c0-63e8-4b51-bf69-dace13e1edc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BLK_DETAIL__FULL_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BLK_DETAIL__FULL_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Customer Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb2b171f-cc92-4caa-8499-16005fee6eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e5e561e-c8c3-4f6c-99d0-6240ddb4cd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TXTro</value>
      <webElementGuid>1c414ecf-1fc3-4f75-8e3c-a7737adaed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewmode</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>64620489-e57f-4397-ad56-ed55da30ee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label_value</name>
      <type>Main</type>
      <value>Customer Name</value>
      <webElementGuid>91d1a59a-f6f9-4aa9-a002-614a65a26440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Customer Name</value>
      <webElementGuid>7124d794-0930-4201-9f9b-20326325ea9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BLK_DETAIL__FULL_NAME</value>
      <webElementGuid>4590dd9b-99c1-44bd-befd-4a115c6731ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dbt</name>
      <type>Main</type>
      <value>BLK_DETAIL</value>
      <webElementGuid>a73d1a69-65f8-4abd-b497-7d74e23b83d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dbc</name>
      <type>Main</type>
      <value>FULL_NAME</value>
      <webElementGuid>8ff363ee-67ad-4d2f-94fa-492d14435ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FULL_NAME</value>
      <webElementGuid>14e0fd04-aff3-4b8d-92d9-8c4d19e15724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dtype</name>
      <type>Main</type>
      <value>VARCHAR2</value>
      <webElementGuid>2962709a-74ea-43f3-bf59-ada99ca230c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>3e06eb4d-3964-417a-95e6-db2a3d866337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>fngettabdetails(event)</value>
      <webElementGuid>a79140b6-422f-4309-b046-a0c083206603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5311b10-5bb5-4b63-beab-d7d3be1e846c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>105</value>
      <webElementGuid>4d957c29-1d67-4450-9fdf-7417ee751747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FULL_NAME_0004302</value>
      <webElementGuid>50be9e27-9c98-49e6-b2dc-a95cabd118f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BLK_DETAIL__FULL_NAME&quot;)</value>
      <webElementGuid>5042d9c4-4726-40ab-861c-aa271a5a6b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_1450fe/iframe_concat(id(, , ifr_LaunchWin_SEC_SUMM_21366a</value>
      <webElementGuid>16e27fa2-aa3f-4c27-9e4f-1826ffab1c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BLK_DETAIL__FULL_NAME']</value>
      <webElementGuid>1e31554e-9545-4817-aecb-bc637a99004f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='BLK_DETAIL']/tbody/tr/td[4]/div/input</value>
      <webElementGuid>413c5b69-c2b3-4d74-b331-79ba4eed022c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>ccb89d2b-9b5a-4f81-89b1-59d452f23c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Customer Name' and @id = 'BLK_DETAIL__FULL_NAME' and @name = 'FULL_NAME']</value>
      <webElementGuid>673eba19-5873-45b6-8b8f-43a7ac19913a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
