<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VALUE_VALUE</name>
   <tag></tag>
   <elementGuidId>142fe1d0-99fb-496b-9001-62cca840848f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BLK_MASTER__VALUE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BLK_MASTER__VALUE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;VALUE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54113989-b4f0-43d9-9091-0e49b75614a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24680de4-a49b-460d-b333-bfa594f24c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TXTstd</value>
      <webElementGuid>526cb768-cac7-4b38-9eb3-121da71e93b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewmode</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>af6a8a4a-666e-4427-bb0e-b35d903572b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>disp_auto_lov('STDCUSUM','BLK_MASTER','VALUE','','LOV_CUST','','','','', this, event)</value>
      <webElementGuid>93ed4ed2-5bb9-407e-8b03-a08468c16119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VALUE</value>
      <webElementGuid>0c64cc5a-35ce-4ecd-951a-49d3a60318fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BLK_MASTER__VALUE</value>
      <webElementGuid>c9df0a76-4972-44fe-9f6b-339e12970c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dbt</name>
      <type>Main</type>
      <value>BLK_MASTER</value>
      <webElementGuid>3b59c480-548d-4ad2-b240-f8a2d5afacc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dbc</name>
      <type>Main</type>
      <value>VALUE</value>
      <webElementGuid>6e7be465-c0e9-4ea5-9646-a83604a0cddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VALUE</value>
      <webElementGuid>bbb2816f-a2cd-4a7b-b215-3d77cd79f6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dtype</name>
      <type>Main</type>
      <value>VARCHAR2</value>
      <webElementGuid>dac331cb-a3fe-422b-baa1-cbee0d81d8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>cd7070a9-4a01-48e3-bd63-069b27d4af17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c7ad57fe-5f6c-4b8e-8bb7-e1f2a566cf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>115</value>
      <webElementGuid>3acfcdf5-a3d9-4439-943a-43afdb501882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4912acb9-cc77-4ac6-aa95-9ea8e08223c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>fnCusShort(event)</value>
      <webElementGuid>7d83991f-8ecf-487e-ac4a-9405263f56cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BLK_MASTER__VALUE&quot;)</value>
      <webElementGuid>28992312-b042-4aaf-b005-973c4e7a56d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_JFOY01 - 000 - 000 - 000 - Oracle Fina_1450fe/iframe_concat(id(, , ifr_LaunchWin_SEC_SUMM_21366a</value>
      <webElementGuid>71539444-735c-4aa1-b6a8-c71c42861fa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BLK_MASTER__VALUE']</value>
      <webElementGuid>e5103990-2aaa-478f-bcaf-e4bbf50948c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TAB_HEADER__SEC_ONE__PAR1']/fieldset/div/div[2]/input</value>
      <webElementGuid>706cc7ea-d375-4f07-b0d1-ccd5d78e2837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>65b7cc22-4977-4df7-a13f-5b4494044e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'VALUE' and @id = 'BLK_MASTER__VALUE' and @name = 'VALUE']</value>
      <webElementGuid>75ffe100-8847-42bc-a7da-e4ecadab4393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
