<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Copyright  2017,2018, Oracle andor i_6a2a69_1</name>
   <tag></tag>
   <elementGuidId>97ed4a29-c3a2-4336-a155-896a306beef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifr_AlertWin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifr_AlertWin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Information Message&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f8162c82-bf19-4238-8e71-b38613d04af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifr_AlertWin</value>
      <webElementGuid>b41944a8-be42-4550-87dc-593e47bf8388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>frames</value>
      <webElementGuid>6d3a96a3-f256-41b7-8345-bce0f975c77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edb704ee-ba42-4dcb-a63f-e857be24877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f6b4385-e88f-49ac-9acb-e8934fe551b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ddcf11df-58cf-4cc8-a7a7-d2befd605284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Information Message</value>
      <webElementGuid>22fa615a-bc1a-48af-905c-d1d2e1c0894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db8cd721-1e8b-4194-ad65-dceb3261b4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c16c9da-e42a-4208-ab8f-edd00161ce6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifr_AlertWin&quot;)</value>
      <webElementGuid>5fe7c7eb-d988-4729-b8ae-397e931a7841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifr_AlertWin']</value>
      <webElementGuid>f436a1f3-974d-45fa-9c90-deccea3a30a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_AlertWin']/iframe</value>
      <webElementGuid>46324d92-43e3-4d61-a7e7-02cdc17c5037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a71c583a-a2f0-4d28-b141-e1f8549c93aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifr_AlertWin' and @title = 'Information Message']</value>
      <webElementGuid>3646e7e3-6990-45d5-8216-830b567f1393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
