<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You are about to log into Test2_Ok (1)</name>
   <tag></tag>
   <elementGuidId>0a0e6385-ac8e-442d-88be-09681bff3cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BTN_OK']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BTN_OK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ok&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86198801-757c-4429-bf2c-b149deb4fbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BTNfooterH</value>
      <webElementGuid>f38bb19c-1bcb-48d4-bb3f-a5b24dc8717f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>53bc8202-3b60-49c7-930b-1aa23d421378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>5414f64e-e004-4efd-a671-c5928be93400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>899e8024-7563-41cd-9661-39e85304b572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BTN_OK</value>
      <webElementGuid>829fabff-6cb8-464c-8ee6-5d23593b12c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>9b9ebd37-235e-4e39-988a-24a0ee0b8db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.className='BTNfooterH'</value>
      <webElementGuid>da4c8741-bbbc-4719-bdc8-48c68e4e33be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>this.className='BTNfooter'</value>
      <webElementGuid>d7f3926c-49d0-44d9-9a22-e65fe11939c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeAlerts(event)</value>
      <webElementGuid>a3696341-9a9d-4e69-99f1-87dc75a61877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return fnHandleAlertBtn(event)</value>
      <webElementGuid>17bad18a-59f5-4fbd-acc7-7c02340184a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>9cd5ffdd-5335-443a-b6d7-8be438f0b374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f867978-6254-4a25-871d-cad05a6bb7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BTN_OK&quot;)</value>
      <webElementGuid>da6d9d41-2b2b-4daf-a361-dd3381bc7a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/Page_Oracle Financial Services/iframe_Copyright  2017,2018, Oracle andor i_6a2a69_1</value>
      <webElementGuid>d690b29b-c75b-4e69-b2a2-bc5bb92355a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BTN_OK']</value>
      <webElementGuid>fdb436b6-0135-4be9-8e1e-3ab165f1cee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='TBLPageTAB_FOOTER']/tbody/tr/td[2]/input</value>
      <webElementGuid>4da32732-30ab-4185-8a24-2be4b06b47ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2354a3e8-7dec-4213-9531-9662ecfd5de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Ok' and @id = 'BTN_OK' and @name = 'Ok' and @type = 'button']</value>
      <webElementGuid>5c44e1ed-d579-4e9c-bfbe-550aebc24ba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
